use_frameworks!

target 'HYDispatchQueuePool_Example' do
  pod 'HYDispatchQueuePool', :path => '../'

  target 'HYDispatchQueuePool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
